version: 0.0
os: linux
files:
  - source: /
    destination: /usr/share/html/nginx/DeployDemo
hooks:
  BeforeInstall:
    - location: script/cleanupfiles.sh
      timeout: 300
      runas: root
    - location: script/start_server.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: script/stop_server.sh
      timeout: 300
      runas: root
                               

